platformName: "Android"
platformVersion: "8.1.0"
appPackage: "com.gengcon.android.jccloudprinter"
appActivity: "melon.south.com.mainlibrary.v.LaunchActivity"
noReset: True
unicodeKeyboard: True
resetKeyboard: True